!!!!!!!!!!!!  GLOBAL :  "Broadcom Corporation"  ==> "Broadcom"

!!!!!!!!!!!!!!!!!!!!  START OF Wrong Chip !!!!!!!!!!!!!!!!!!


INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Alltek", "53018_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Altiostar", "53012_A2");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Avnet Inc", "56450_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Avnet Inc, Other", "AllChips");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "2000_A1");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "3200_B0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "53001_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "53003_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "53010_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "53010_A1");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "53011_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "53011_A2");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "53012_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "53012_A1");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "53012_A2");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "53018_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "53019_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "53022_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "53025_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "53084_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "53125_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "53346_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "53400_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "53403_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "5389_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "5398_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "56060");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "56150_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "56151_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "56340_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "56344_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "56450_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "56504_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "56540_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "56547_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "56580_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "56830_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "5695_B0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "5880_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "5880_B0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "5892_C0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "88030_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "89500_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "AllChips");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "Lynx");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "Lynx1.5");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "NA");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "None");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation, Ubiquiti Networks", "NA");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Ericson", "NA");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "FASTPATH", "56150_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "FASTPATH", "56340_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "FASTPATH", "56548_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "FASTPATH", "NA");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "FastPath", "53011_A2");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "FastPath", "56340_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Fastpath", "56340_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Huawei", "56450_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "LANDI", "AllChips");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Netgear", "56150_A0");


!!!!!!!!!!!!!!!!!!!!  END  OF Wrong Chip !!!!!!!!!!!!!!!!!!


!!!!!!!!!!!!!!!!!!!!  START OF Right Chip !!!!!!!!!!!!!!!!!!


INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "5218");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "5220");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "5221");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "5226");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "5228");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "5238");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "5248");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "56060");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "11360_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "11360_B0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "2000_A1");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "3200_B0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "52681E_A1");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "53001_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "53003_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "53010_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "53010_A1");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "53010_A2");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "53011_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "53011_A1");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "53011_A2");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "53012_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "53012_A1");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "53012_A2");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "53017_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "53018_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "53019_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "53022_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "53023_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "53025_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "53084_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "53125_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "53125_B0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "53344_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "53346_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "53400_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "53403_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "53406_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "5389_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "5398_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "56150_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "56151_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "56340_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "56342_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "56344_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "56450_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "56450_B0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "56455_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "56456_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "56504_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "56540_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "56547_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "56548_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "56580_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "56830_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "56830_A1");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "56830_A2");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "5695_B0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "58300_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "58300_B0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "58302_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "58302_B0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "5880_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "5892_C0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "88030_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "88030_B0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "89500_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "ALL");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "Lynx");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "Lynx1.5");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "NA");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "Costar");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "Cygnus");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "Greyhound");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "Helix4");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "Helix4-BE");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "Hurricane2");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "Katana2");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "Northstar");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "Northstar ");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "Northstar+");


!!!!!!!!!!!!!!!!!!!!  END OF Right Chip !!!!!!!!!!!!!!!!!!

INSERT IGNORE INTO Customer (Project, Product, Value) VALUES ("SOC", "IPROCSW", "Alltek");
INSERT IGNORE INTO Customer (Project, Product, Value) VALUES ("SOC", "IPROCSW", "Altiostar");
INSERT IGNORE INTO Customer (Project, Product, Value) VALUES ("SOC", "IPROCSW", "Avnet Inc");
!!!!!!!!!!WRONG!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  INSERT IGNORE INTO Customer (Project, Product, Value) VALUES ("SOC", "IPROCSW", "Avnet Inc, Other");
!!!!!!!!!!WRONG!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  INSERT IGNORE INTO Customer (Project, Product, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation");
!!!!!!!!!!WRONG!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  INSERT IGNORE INTO Customer (Project, Product, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation, Ubiquiti Networks");
!!!!!!!!!!WRONG!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  INSERT IGNORE INTO Customer (Project, Product, Value) VALUES ("SOC", "IPROCSW", "Ericson");
!!!!!!!!!!WRONG!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  INSERT IGNORE INTO Customer (Project, Product, Value) VALUES ("SOC", "IPROCSW", "FASTPATH");
!!!!!!!!!!WRONG!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  INSERT IGNORE INTO Customer (Project, Product, Value) VALUES ("SOC", "IPROCSW", "FastPath");
!!!!!!!!!!WRONG!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  INSERT IGNORE INTO Customer (Project, Product, Value) VALUES ("SOC", "IPROCSW", "Fastpath");
INSERT IGNORE INTO Customer (Project, Product, Value) VALUES ("SOC", "IPROCSW", "Huawei");
INSERT IGNORE INTO Customer (Project, Product, Value) VALUES ("SOC", "IPROCSW", "LANDI");
INSERT IGNORE INTO Customer (Project, Product, Value) VALUES ("SOC", "IPROCSW", "Netgear");
!!!!!!!!!!WRONG!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!   INSERT IGNORE INTO Customer (Project, Product, Value) VALUES ("SOC", "POS", "Broadcom Corporation");


!!!!!!!!!!!!  START OF MORE CUSTOMERS !!!!!!!!!!!!!!!!!

INSERT IGNORE INTO Customer (Project, Product, Value) VALUES ("SOC", "IPROCSW", "Broadcom");

INSERT IGNORE INTO Customer (Project, Product, Value) VALUES ("SOC", "IPROCSW", "Avnet Inc");
INSERT IGNORE INTO Customer (Project, Product, Value) VALUES ("SOC", "IPROCSW", "Ericsson");
INSERT IGNORE INTO Customer (Project, Product, Value) VALUES ("SOC", "IPROCSW", "Ubiquiti Networks");

INSERT IGNORE INTO Customer (Project, Product, Value) VALUES ("SOC", "POS", "Broadcom");

!!!!!!!!!!!!!!!!! END OF More Customers !!!!!!!!!!!!!!!!!!!!!!!!

INSERT IGNORE INTO Product (Project, Value) VALUES ("SOC", "IPROCSW");
INSERT IGNORE INTO Product (Project, Value) VALUES ("SOC", "POS");

!!!!!!!!!!!!!!!!!!!!!!!!!!!!  START OF WRONG RELEASES !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!


INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Alltek", "3.4.3");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Altiostar", "3.3.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Avnet Inc", "3.4.5-RC3");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Avnet Inc, Other", "3.5.4_RC2");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "0.1.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "0.2.1");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "0.3.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "0.4.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "0.5.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "0.6.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "1.0.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "1.2.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "1.3.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "1.4.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "1.5.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "1.6.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "2.0.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "2.0.1");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "2.0.2");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "3.0.3");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "3.0.5");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "3.0.6");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "3.1.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "3.1.1");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "3.1.1.pae");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "3.1.2");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "3.2.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "3.2.1");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "3.2.2");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "3.2.3");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "3.2.4");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "3.3.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "3.3.1");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "3.4.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "3.4.2");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "3.4.3");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "3.4.4");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "3.4.4-RC1");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "3.4.4-RC2");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "3.4.4-RC3");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "3.4.5-RC1");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "3.4.5-RC2");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "3.4.5-RC3");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "3.4.6");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "3.4.7-RC4");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "3.4.7_RC1");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "3.4.7_RC2");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "3.4.7_RC3");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "3.4.8_RC1");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "3.4.8_RC2");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "3.4.9_RC1");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "3.4.9_RC3");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "3.4.9_RC4_ALPHA");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "3.4.9_RC6");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "3.4.9_RC7");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "3.4.9_RC7_GA");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "3.4.9_RC8");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "3.5.0_RC1");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "3.5.0_RC2");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "3.5.1_RC1");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "3.5.2_RC2");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "3.5.3_RC1");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "3.5.3_RC2");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "3.5.4_RC1");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "3.5.4_RC2");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "3.5.5_RC1");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "3.5.5_RC2");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "3.5.5_RC3");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "3.5.6_RC1");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "LDK_3.5.x_b0_bringup");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "SBL_0.3");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "SBL_0.4");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "SBL_0.5");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "SBL_0.6");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "SBL_0.7");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "SBL_0.8");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "SBL_1.2");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "SBL_CYG_B0_2.1");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "SBL_CYG_B0_2.3");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "SBL_CYG_B0_2.5.1");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "SBL_LYNX_A0_5.002");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "SBL_LYX_A0_5.001");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "SBL_NSP_B0_3.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "TBD");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation", "open_3.4.1");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation, Ubiquiti Networks", "3.4.5-RC3");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom Corporation, Ubiquiti Networks", "3.4.9_RC7");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Ericson", "3.4.9_RC7");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Ericson", "3.5.3_RC2");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "FASTPATH", "3.2.4");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "FASTPATH", "3.3.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "FASTPATH", "3.4.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "FASTPATH", "3.4.2");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "FASTPATH", "3.4.4");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "FastPath", "3.1.2");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "FastPath", "3.2.4");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "FastPath", "3.3.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "FastPath", "3.3.1");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "FastPath", "3.4.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "FastPath", "3.4.2");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "FastPath", "3.4.3");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "FastPath", "3.4.4");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "FastPath", "3.4.5-RC3");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Fastpath", "3.4.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Huawei", "3.4.6");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Huawei", "3.4.8_RC1");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Huawei", "3.4.9_RC7");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "LANDI", "3.5.3_RC2");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Netgear", "3.2.4");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Netgear", "3.3.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Netgear", "3.3.1");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "POS", "Broadcom Corporation", "5.0.5");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "POS", "Broadcom Corporation", "5.2.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "POS", "Broadcom Corporation", "5.2.1");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "POS", "Broadcom Corporation", "5.2.2");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "POS", "Broadcom Corporation", "5.2.3");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "POS", "Broadcom Corporation", "5.2.4");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "POS", "Broadcom Corporation", "5.2.5");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "POS", "Broadcom Corporation", "5.2.6");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "POS", "Broadcom Corporation", "5.2.7");


!!!!!!!!!!!!!!!!!!!!!!!!!!!!  END OF WRONG RELEASES !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

!!!!!!!!!!!!!!!!!!!!!!!!!!!!  START OF RIGHT RELEASES !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "IPROC-0.1.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "IPROC-0.2.1");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "IPROC-0.3.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "IPROC-0.4.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "IPROC-0.5.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "IPROC-0.6.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "IPROC-1.0.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "IPROC-1.2.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "IPROC-1.3.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "IPROC-1.4.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "IPROC-1.5.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "IPROC-1.6.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "IPROC-2.0.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "IPROC-2.0.1");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "IPROC-2.0.2");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "IPROC-3.0.3");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "IPROC-3.0.5");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "IPROC-3.0.6");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "IPROC-3.1.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "IPROC-3.1.1");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "IPROC-3.1.2");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "IPROC-3.2.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "IPROC-3.2.1");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "IPROC-3.2.2");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "IPROC-3.2.3");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "IPROC-3.2.4");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "IPROC-3.3.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "IPROC-3.3.1");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "IPROC-3.4.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "IPROC-3.4.1");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "IPROC-3.4.2");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "IPROC-3.4.3");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "IPROC-3.4.4");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "IPROC-3.4.5");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "IPROC-3.4.6");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "IPROC-3.4.7");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "IPROC-3.4.8");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "IPROC-3.4.9");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "IPROC-3.5.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "IPROC-3.5.1");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "IPROC-3.5.2");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "IPROC-3.5.3");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "IPROC-3.5.4");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "IPROC-3.5.5");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "IPROC-3.5.6");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "IPROCSW", "Broadcom", "NOT IMPORTED");



INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "POS", "Broadcom", "POS-5.0.5");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "POS", "Broadcom", "POS-5.2.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "POS", "Broadcom", "POS-5.2.1");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "POS", "Broadcom", "POS-5.2.2");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "POS", "Broadcom", "POS-5.2.3");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "POS", "Broadcom", "POS-5.2.4");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "POS", "Broadcom", "POS-5.2.5");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "POS", "Broadcom", "POS-5.2.6");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("SOC", "POS", "Broadcom", "POS-5.2.7");


!!!!!!!!!!!!!!!!!!!!!!!!!!!!  END OF RIGHT RELEASES !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!



!!!!!!!!!!!!!!!!!!!!!!!!!!!!  START OF WRONG COMPONENTS  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "Application request cygnus");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "Application request northstar+");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "Application request");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "BE (KT2) katana2 linux");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "NS B0 pcie");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "audio (I2s/TDM/Codec)");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "board diags cygnus pcie");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "board diags cygnus uboot usb2-H");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "board diags cygnus uboot");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "board diags cygnus");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "board diags");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "buildroot/package/Compiler/Docs cygnus linux");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "buildroot/package/Compiler/Docs cygnus");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "buildroot/package/Compiler/Docs linux northstar performance");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "buildroot/package/Compiler/Docs linux");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "buildroot/package/Compiler/Docs northstar");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "buildroot/package/Compiler/Docs northstar+");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "buildroot/package/Compiler/Docs scripts/regression");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "buildroot/package/Compiler/Docs");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "busybox");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "camera cygnus");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "cfe");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "costar helix4 hurricane2 katana2 northstar northstar+");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "costar linux");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "costar northstar");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "costar shmoo");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "costar uboot");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "costar usb3-H");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "cygnus dma");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "cygnus documents");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "cygnus ethernet, gmac, switch linux");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "cygnus ethernet, gmac, switch");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "cygnus gmac-uboot uboot");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "cygnus gpio pwr mgmt");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "cygnus gpio");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "cygnus keypad touch/ADC");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "cygnus keypad");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "cygnus linux nand-linux pwr mgmt");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "cygnus linux pwr mgmt qspi");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "cygnus linux pwr mgmt");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "cygnus linux");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "cygnus nand-linux uboot");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "cygnus nand-linux");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "cygnus nand-uboot");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "cygnus northstar+ northstar2 uboot");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "cygnus northstar+");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "cygnus pcie");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "cygnus pka");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "cygnus pwr mgmt");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "cygnus release notes");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "cygnus sbi");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "cygnus sbl");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "cygnus sbl-usb");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "cygnus sdio3");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "cygnus smart card");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "cygnus spum,crypto");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "cygnus trustzone");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "cygnus uboot");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "cygnus usb2-H");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "cygnus usbd");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "cygnus");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "dma");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "documents");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "ethernet, gmac, switch helix4 linux");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "ethernet, gmac, switch helix4");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "ethernet, gmac, switch hurricane2");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "ethernet, gmac, switch linux wlan");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "ethernet, gmac, switch linux");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "ethernet, gmac, switch northstar northstar+");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "ethernet, gmac, switch northstar+");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "ethernet, gmac, switch uboot");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "ethernet, gmac, switch");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "external sata (PCIe ASMMedia) hurricane2");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "external sata (PCIe ASMMedia) linux northstar+");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "external sata (PCIe ASMMedia)");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "fa linux wlan");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "fa pae-fw");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "fa");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "gmac-uboot linux northstar+");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "gpio hurricane2");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "greyhound linux uboot");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "greyhound nand-linux nand-uboot");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "greyhound usbd");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "greyhound");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "helix4 hurricane2 katana2 linux");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "helix4 hurricane2 katana2");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "helix4 hurricane2 northstar+ shmoo uboot");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "helix4 katana2 linux");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "helix4 linux nand-linux nand-uboot uboot");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "helix4 linux");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "helix4 nand-uboot uboot");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "helix4 nand-uboot");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "helix4 pcie");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "helix4 uboot");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "helix4 usb2-H");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "helix4");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "helix4-BE nand-uboot");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "helix4-BE");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "hurricane2 linux pcie uboot");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "hurricane2 linux");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "hurricane2 nor uboot");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "hurricane2 nor");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "hurricane2 pcie");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "hurricane2 uboot");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "hurricane2");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "hurricane3 linux uboot");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "katana2 uboot");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "katana2");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "linux nand-linux nand-uboot uboot");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "linux nand-linux northstar+");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "linux nas northstar");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "linux northstar northstar+ performance");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "linux northstar");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "linux northstar+");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "linux otp rng");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "linux performance");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "linux saber2");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "linux smbus(i2c)");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "linux uboot");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "linux");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "mpos");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "nand-linux nand-uboot northstar");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "nand-linux nand-uboot");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "nand-linux pae-ipsec");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "nand-linux");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "nand-uboot northstar+");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "nand-uboot qspi");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "nand-uboot uboot");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "nand-uboot");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "nas");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "nor");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "northstar northstar+ performance");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "northstar northstar+");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "northstar qspi");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "northstar uboot");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "northstar");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "northstar+ B0");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "northstar+ pae-fw");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "northstar+ pae-ipsec");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "northstar+ sbl");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "northstar+ uboot");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "northstar+");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "otp");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "pae-fw pae-ipsec");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "pae-fw");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "pae-ipsec");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "pae-xor");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "pcie uboot");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "pcie");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "performance");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "qspi");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "rng sata");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "sata");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "sbl sbl-halapi sbl-usb");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "sbl sbl-halapi");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "sbl");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "sbl-halapi");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "sbl-usb");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "scripts/regression");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "sdio3");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "smbus(i2c) uboot");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "smbus(i2c)");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "uboot usb2-H");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "uboot");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "usb2-H");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "usb3-H");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "usbd");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "POS", "BCM5892 D0");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "POS", "BCM5892 Linux U-Boot");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "POS", "BCM5892 Linux otg");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "POS", "BCM5892 Linux");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "POS", "BCM5892 ethernet Linux U-Boot");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "POS", "BCM5892 otg");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "POS", "BCM5892");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "POS", "D0 Linux sbi StageII");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "POS", "D0");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "POS", "Linux StageII");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "POS", "Linux");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "POS", "StageII");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "POS", "U-Boot");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "POS", "ethernet");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "POS", "filesystem");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "POS", "otg");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "POS", "sbi");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "POS", "usbd");



!!!!!!!!!!!!!!!!!!!!!!!!!!!!  END OF WRONG COMPONENTS  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!



!!!!!!!!!!!!!!!!!!!!!!!!!!!!  END OF RIGHT COMPONENTS  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!


INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "Application request");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "Audio (I2s/TDM/Codec)");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "BE (KT2)");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "Board Diags");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "buildroot/package/Compiler/Docs");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "Busybox");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "Camera");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "CAN");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "CFE");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "D1W");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "DMA");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "Ethernet");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "External SATA (PCIe ASMMedia)");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "FA");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "GIC");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "GMAC");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "GMAC-Uboot");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "GPIO");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "I2C");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "Keypad");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "LCD");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "MG");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "MPOS");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "NAND-Linux");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "NAND-Uboot");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "NAS");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "NOR");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "NOT_IMPORTED");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "OTP");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "PAE-FW");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "PAE-IPSEC");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "PAE-XOR");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "PCIE");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "Performance");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "PKA");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "Power Mgmt");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "QSPI");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "RTC");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "SATA");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "SBI");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "SBL");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "SBL-Halapi");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "SBL-USB");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "Scripts/Regression");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "SDIO3");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "Smartcard");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "SMBUS (I2C)");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "SPUM");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "Timer");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "TouchScreen");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "TrustZone");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "Uboot");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "USB2-H");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "USB3-H");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "IPROCSW", "USBD");



INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "POS", "Ethernet");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "POS", "File system");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "POS", "NOT_IMPORTED");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "POS", "OTG");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "POS", "SBI");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "POS", "Stage II");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "POS", "Uboot");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("SOC", "POS", "USBD");

!!!!!!!!!!!!!!!!!!!!!!!!!!!!  END OF RIGHT COMPONENTS  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
