/* Chip */
DELETE FROM Chip WHERE Project = "CTRL" AND idChip != 0;
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","4401");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","4401_A1");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","4401_A2");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","4401_B0");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","4401_B1");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","4401_E0");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5714");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5714S");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5714S_A0");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5714S_A1");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5714S_A2");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5714S_A3");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5714_A0");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5714_A1");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5714_A2");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5714_A3");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5714_A4");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5714_B0");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5715");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5715S");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5715S_A1");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5715S_A2");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5715S_A3");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5715S_B0");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5715_A0");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5715_A1");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5715_A2");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5715_A3");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5715_B0");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5716");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5716_A1");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5717");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5717S");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5717S_A0");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5717_A0");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5717_A1");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5717_B0");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5717_C0");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5718");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5718_A0");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5718_A1");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5718_B0");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5718_C0");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5718_E0");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5719");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5719_A0");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5719_A1");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5719_A2");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5719_A5");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5719_B0");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5719_E0");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5720");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5720_A0");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5720_A1");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5720_A2");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5720_B0");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5721");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5721_A0");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5721_A1");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5721_A2");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5721_A3");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5721_A4");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5721_B0");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5721_B1");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5721_C0");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5721_C1");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5722");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5722_A0");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5722_A1");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5722_A2");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5722_B0");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5722_B1");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5722_C0");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5723");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5723_A0");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5723_A1");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5723_B0");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5723_B1");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5724_A0");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5725");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5725_A0");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5725_A1");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5725_B0");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5727");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5727_B0");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5750");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5750_A0");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5750_A1");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5750_A3");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5750_A4");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5751");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5751F");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5751F_A0");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5751F_A1");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5751F_B0");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5751F_B1");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5751F_C1");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5751M");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5751M_A1");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5751M_A4");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5751M_B0");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5751M_B1");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5751M_C0");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5751M_C1");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5751_A0");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5751_A1");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5751_A2");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5751_A3");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5751_A4");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5751_A5");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5751_B0");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5751_B1");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5751_B2");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5751_C0");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5751_C1");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5751_C2");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5752");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5752M");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5752M_A2");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5752_A0");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5752_A1");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5752_A2");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5752_A3");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5752_B1");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5753");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5753M_A1");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5753M_A2");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5753M_C1");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5753M_C2");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5753_A1");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5753_A2");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5753_A4");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5753_B1");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5753_B3");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5753_C0");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5753_C1");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5754");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5754M_A2");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5754_A0");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5754_A1");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5754_A2");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5755");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5755M");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5755M_A0");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5755M_A1");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5755M_A2");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5755_A0");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5755_A1");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5755_A2");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5756ME");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5756ME_A0");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5756ME_A1");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5756ME_A2");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5756ME_B0");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5760");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5760_A0");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5760_A1");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5760_B0");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5761");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5761E_A0");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5761E_A2");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5761E_B0");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5761M");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5761M_A0");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5761M_A2");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5761M_B0");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5761M_B1");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5761S_B0");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5761_A0");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5761_A1");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5761_A2");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5761_B0");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5761_B1");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5761_B2");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5762");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5762_A0");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5762_A1");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5762_B0");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5764M");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5764M_A0");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5764M_A1");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5764M_B0");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5764M_B1");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","57760");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","57760_A0");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","57760_A1");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","57760_A2");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","57760_B0");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","57761_A0");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","57761_B0");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","57762");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","57762_A0");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","57762_A1");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","57762_B0");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","57762_C0");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","57765");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","57765_A0");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","57765_A1");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","57765_B0");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","57765_E0");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","57766_A0");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","57766_A1");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","57766_B0");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","57766_C0");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","57767_A0");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","57767_A1");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","57767_B0");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","57780");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","57780_A0");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","57780_A1");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","57780_B0");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","57781_A0");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","57781_A1");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","57781_B0");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","57782_A0");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","57782_A1");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","57785");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","57785_A0");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","57785_A1");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","57785_B0");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","57785_B1");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","57785_E0");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","57786x_A0");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","57786x_A1");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","57786x_B0");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","57786x_C0");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","57787_A0");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","57787_B0");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","57788_A1");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","57788_B0");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","57790_A0");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","57790_A1");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","57790_A2");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","57791");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","57795_A0");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5782_A1");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5782_A2");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5782_A3");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5784M");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5784M_A0");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5784M_A1");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5784M_A2");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5784M_B0");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5785");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5785_A0");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5785_A1");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5785_B0");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5786");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5786_A0");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5786_A2");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5786_A3");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5787");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5787F_A2");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5787M");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5787M_A1");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5787M_A2");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5787_A0");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5787_A1");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5787_A2");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5788");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5788_A1");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5788_A3");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5788_A5");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5788_B0");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5789");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5789_B0");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5789_B1");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5789_C0");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5789_C1");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5901_A0");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5901_A1");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5903M_C2");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5906");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5906M");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5906M_A0");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5906M_A1");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5906M_A2");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5906M_B2");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5906_A0");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5906_A1");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","5906_A2");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BLANK");
INSERT IGNORE INTO Chip (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","N/A");

/* Customer */
DELETE FROM Customer WHERE Project = "CTRL" AND idCustomer != 0;
INSERT IGNORE INTO Customer (Project,Product,Value) VALUES ("CTRL","NetXtreme I","Broadcom");
INSERT IGNORE INTO Customer (Project,Product,Value) VALUES ("CTRL","NetXtreme I","IBM Server");
INSERT IGNORE INTO Customer (Project,Product,Value) VALUES ("CTRL","NetXtreme I","Amazon");
INSERT IGNORE INTO Customer (Project,Product,Value) VALUES ("CTRL","NetXtreme I","Other");
INSERT IGNORE INTO Customer (Project,Product,Value) VALUES ("CTRL","NetXtreme I","Acer");
INSERT IGNORE INTO Customer (Project,Product,Value) VALUES ("CTRL","NetXtreme I","Apple");
INSERT IGNORE INTO Customer (Project,Product,Value) VALUES ("CTRL","NetXtreme I","Dell Desktop");
INSERT IGNORE INTO Customer (Project,Product,Value) VALUES ("CTRL","NetXtreme I","Dell Mobile");
INSERT IGNORE INTO Customer (Project,Product,Value) VALUES ("CTRL","NetXtreme I","Dell Server");
INSERT IGNORE INTO Customer (Project,Product,Value) VALUES ("CTRL","NetXtreme I","EMC");
INSERT IGNORE INTO Customer (Project,Product,Value) VALUES ("CTRL","NetXtreme I","Foxconn");
INSERT IGNORE INTO Customer (Project,Product,Value) VALUES ("CTRL","NetXtreme I","Fujitsu");
INSERT IGNORE INTO Customer (Project,Product,Value) VALUES ("CTRL","NetXtreme I","HP Desktop");
INSERT IGNORE INTO Customer (Project,Product,Value) VALUES ("CTRL","NetXtreme I","HP Mobile");
INSERT IGNORE INTO Customer (Project,Product,Value) VALUES ("CTRL","NetXtreme I","HP Server");
INSERT IGNORE INTO Customer (Project,Product,Value) VALUES ("CTRL","NetXtreme I","HP Workstation");
INSERT IGNORE INTO Customer (Project,Product,Value) VALUES ("CTRL","NetXtreme I","Hitachi");
INSERT IGNORE INTO Customer (Project,Product,Value) VALUES ("CTRL","NetXtreme I","HuaWei");
INSERT IGNORE INTO Customer (Project,Product,Value) VALUES ("CTRL","NetXtreme I","IBM Desktop");
INSERT IGNORE INTO Customer (Project,Product,Value) VALUES ("CTRL","NetXtreme I","Inventec");
INSERT IGNORE INTO Customer (Project,Product,Value) VALUES ("CTRL","NetXtreme I","Lenovo Desktop");
INSERT IGNORE INTO Customer (Project,Product,Value) VALUES ("CTRL","NetXtreme I","Lenovo Mobile");
INSERT IGNORE INTO Customer (Project,Product,Value) VALUES ("CTRL","NetXtreme I","Lenovo Server");
INSERT IGNORE INTO Customer (Project,Product,Value) VALUES ("CTRL","NetXtreme I","MSI");
INSERT IGNORE INTO Customer (Project,Product,Value) VALUES ("CTRL","NetXtreme I","Microsoft");
INSERT IGNORE INTO Customer (Project,Product,Value) VALUES ("CTRL","NetXtreme I","Mitec");
INSERT IGNORE INTO Customer (Project,Product,Value) VALUES ("CTRL","NetXtreme I","NEC");
INSERT IGNORE INTO Customer (Project,Product,Value) VALUES ("CTRL","NetXtreme I","NOT_IMPORTED");
INSERT IGNORE INTO Customer (Project,Product,Value) VALUES ("CTRL","NetXtreme I","Quanta");
INSERT IGNORE INTO Customer (Project,Product,Value) VALUES ("CTRL","NetXtreme I","Vmware");
INSERT IGNORE INTO Customer (Project,Product,Value) VALUES ("CTRL","NetXtreme I","Wistron");

/* Document */
DELETE FROM Document WHERE Project = "CTRL" AND idDocument != 0;

/* Fixed_in_Chip_Revision */
DELETE FROM Fixed_in_Chip_Revision WHERE Project = "CTRL" AND idFixed_in_Chip_Revision != 0;

/* Hardware_Board_Revision */
DELETE FROM Hardware_Board_Revision WHERE Project = "CTRL" AND idHardware_Board_Revision != 0;
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM57760T6000G v0.0 REV P5");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM57780T8000G v0.0 REV P5");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM94401 Rev. 001");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM94401 V2.0");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM94401 V3.0");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM94401A10 v3.0 revA0");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM94401A10 v3.0 revA1");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM94401A10 v3.0 revA2");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM94401A10 v4.0 revA1");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM94401A10 v5.0 revA0");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM94401A20F v0.0 revA0");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM94401ET0101 v0.0 revP1");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM94401ET0101 v0.0 revP3");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM94401T41 v0.0 rev000");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM95701A10 Rev. 001");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM95701A10C v3.0 revA4");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM95703A030U v0.0 revA0");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM95703A30U v4.0 revA3");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM95703A30U v6.0 revA0");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM95703A30U v6.1 revA0");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM95703A30U v8.0 revA4");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM95703A30U v9.0 revA1");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM95703SA31U v2.0 rev004");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM95703SA31U v2.0 rev005");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM95703T033 v0.0 revP3");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM95704A40 v1.0 revA3");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM95704CA40 v1.0 revA0");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM95704CA40 v1.0 revA2");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM95704CA40 v2.0 revA1");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM95704CA40 v3.0 revA0");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM95704CA40 v3.0 revA3");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM95709A0930G");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM95709SA0930G");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM957101T0100G");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM95714 v0.02 revB");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM95714S v0.01 revA");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM95714ST144 v0.0 revP4");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM95714T143 v1.0 revP1");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM95714T143 v1.0 revP3");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM95715A155F v0.0 revP1");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM95715ST154 v1.0 revP2");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM95717T1700G Rev P4");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM95718 T1800G Rev P6");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM95718A1805G");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM95718T1800G Rev P4");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM95719A1904G");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM95719A1904G_C");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM95719A1904G_D");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM95719A1904G_H");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM95719A1904G_I");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM95719A1905G");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM95719T1900G rev P3");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM95719T900G rev P5");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM95720A2003G");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM95720A2003G_C");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM95720A2003G_D");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM95720A2003G_H");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM95720A2003G_I");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM95720T2000G rev P2.");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM95721T210 v2.0 revA1");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM95721T210 v3.0 revA1");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM95721T2101 v0.0 revP2");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM95722T2200G v0.0 revP3");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM95724T2400G rev P5");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM95725T2500G");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM95727T2700G Rev01");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM95750T503 v0.0 revA1");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM95750T503 v0.0 revA2");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM95750T503 v0.0 revA5");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM95751A519 v1.0 revA0");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM95751FA519 v0.0 revA0");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM95751MT515 v0.0 revA0");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM95751T5101 v0.0 revP3");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM95751T512 v2.0 rev000");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM95751T512 v2.0 revA3");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM95751T512 v3.0 revA2");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM95751T512 v4.0 revA1");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM95751T512 v4.0 revA2");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM95752T5200 v0.0 revP5");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM95752T5204 v0.0 revP1");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM95753T5301 v0.0 revP1");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM95754MT5400 rev P3");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM95754T5400 v0.0 revP1");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM95754T5404 v0.0 revP3");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM95754T5404 v2.0 revP1");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM95755MT5506 v0.0 revP1");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM95755T5501 v2.0 revP1");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM95756MET5600F v0.0 revP1");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM95761A6110G rev P4");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM95761A6110G v0.0 revP2");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM95761A6110G");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM95761ET6103G v0.0 revP3");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM95761T6100G v0.0 rev P7");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM95762T6200G");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM95764MT6401G v0.0 revP5");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM957710A1021G");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM957760T6000G v0.0 REV P3");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM957761T6100G rev P1");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM957762T6200G rev P1");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM957765T6500G");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM957765XT6500G rev P2");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM957765XT6500G rev P4");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM957766T6600G rev P1");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM957766T6600G rev P4");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM957767T6700G");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM957780T8000G v0.0 REV P4");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM957781T8100G rev P1");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM957782T8200G rev P1");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM957785T8500G rev P2");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM957785T8500G");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM957785XT8500G rev P2");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM957785XT8500G rev P4");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM957785XT8500G rev P5");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM957785XT8500G");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM957786XT8600G rev P1");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM957787T8700G");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM957795T9500G rev P2");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM957800T0000G");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM957810A1006G");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM95782A50-H v0.0 revA1");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM95782A50-H v1.0 revA0");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM95782A50-H v1.0 revA1");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM95782A50-H v2.0 revA1");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM9578401g v0.0 revP4");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM957840T4000G");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM95786T8600 v0.0 revP1");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM95787MT8704 v2.0 revP2");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM95787T8701 v0.0 revP3");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM95788A50 v1.0 revA2");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM95901T57 v0.0 rev000");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM95906MT0604F v0.0 revP3");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM95906T0600 v0.0 revP2");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM95906T0600F v0.0 revP3");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM9751T5101 v0.0 revP1");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BCM9751T5101 v0.0 revP2");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BLANK");
INSERT IGNORE INTO Hardware_Board_Revision (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","NOT_IMPORTED-CTRL SPECIFY");

/* OS */
DELETE FROM OS WHERE Project = "CTRL" AND idOS != 0;
INSERT IGNORE INTO OS (Project,Value) VALUES ("CTRL","BLANK");
INSERT IGNORE INTO OS (Project,Value) VALUES ("CTRL","DOS");
INSERT IGNORE INTO OS (Project,Value) VALUES ("CTRL","Mac OS X Snow Leopard");
INSERT IGNORE INTO OS (Project,Value) VALUES ("CTRL","Red Hat EL 5.10");
INSERT IGNORE INTO OS (Project,Value) VALUES ("CTRL","Red Hat EL 5.11");
INSERT IGNORE INTO OS (Project,Value) VALUES ("CTRL","Red Hat EL 5.5");
INSERT IGNORE INTO OS (Project,Value) VALUES ("CTRL","Red Hat EL 5.7");
INSERT IGNORE INTO OS (Project,Value) VALUES ("CTRL","Red Hat EL 5.8");
INSERT IGNORE INTO OS (Project,Value) VALUES ("CTRL","Red Hat EL 5.9");
INSERT IGNORE INTO OS (Project,Value) VALUES ("CTRL","Red Hat EL 6.0");
INSERT IGNORE INTO OS (Project,Value) VALUES ("CTRL","Red Hat EL 6.1");
INSERT IGNORE INTO OS (Project,Value) VALUES ("CTRL","Red Hat EL 6.2");
INSERT IGNORE INTO OS (Project,Value) VALUES ("CTRL","Red Hat EL 6.3");
INSERT IGNORE INTO OS (Project,Value) VALUES ("CTRL","Red Hat EL 6.4");
INSERT IGNORE INTO OS (Project,Value) VALUES ("CTRL","Red Hat EL 6.5");
INSERT IGNORE INTO OS (Project,Value) VALUES ("CTRL","Red Hat EL 7.0");
INSERT IGNORE INTO OS (Project,Value) VALUES ("CTRL","SUSE Linux ES 10.3");
INSERT IGNORE INTO OS (Project,Value) VALUES ("CTRL","SUSE Linux ES 10.4");
INSERT IGNORE INTO OS (Project,Value) VALUES ("CTRL","SUSE Linux ES 11.0");
INSERT IGNORE INTO OS (Project,Value) VALUES ("CTRL","SUSE Linux ES 11.1");
INSERT IGNORE INTO OS (Project,Value) VALUES ("CTRL","SUSE Linux ES 11.2");
INSERT IGNORE INTO OS (Project,Value) VALUES ("CTRL","SUSE Linux ES 11.3");
INSERT IGNORE INTO OS (Project,Value) VALUES ("CTRL","SUSE Linux ES 12.0");
INSERT IGNORE INTO OS (Project,Value) VALUES ("CTRL","Solaris 10");
INSERT IGNORE INTO OS (Project,Value) VALUES ("CTRL","Solaris 11");
INSERT IGNORE INTO OS (Project,Value) VALUES ("CTRL","VMware ESX 4.0");
INSERT IGNORE INTO OS (Project,Value) VALUES ("CTRL","VMware ESX 4.1");
INSERT IGNORE INTO OS (Project,Value) VALUES ("CTRL","VMware ESX 5.0");
INSERT IGNORE INTO OS (Project,Value) VALUES ("CTRL","VMware ESX 5.1");
INSERT IGNORE INTO OS (Project,Value) VALUES ("CTRL","VMware ESX 5.5");
INSERT IGNORE INTO OS (Project,Value) VALUES ("CTRL","VMware ESX 6.0");
INSERT IGNORE INTO OS (Project,Value) VALUES ("CTRL","Windows 2008 IA64");
INSERT IGNORE INTO OS (Project,Value) VALUES ("CTRL","Windows 2008 R2 IA64");
INSERT IGNORE INTO OS (Project,Value) VALUES ("CTRL","Windows 2008 R2 x64");
INSERT IGNORE INTO OS (Project,Value) VALUES ("CTRL","Windows 2008 x64");
INSERT IGNORE INTO OS (Project,Value) VALUES ("CTRL","Windows 2008 x86");
INSERT IGNORE INTO OS (Project,Value) VALUES ("CTRL","Windows 2012 R2");
INSERT IGNORE INTO OS (Project,Value) VALUES ("CTRL","Windows 2012");
INSERT IGNORE INTO OS (Project,Value) VALUES ("CTRL","Windows 7");
INSERT IGNORE INTO OS (Project,Value) VALUES ("CTRL","Windows 8");
INSERT IGNORE INTO OS (Project,Value) VALUES ("CTRL","Windows 8.1");
INSERT IGNORE INTO OS (Project,Value) VALUES ("CTRL","Windows PE");
INSERT IGNORE INTO OS (Project,Value) VALUES ("CTRL","Windows Vista");
INSERT IGNORE INTO OS (Project,Value) VALUES ("CTRL","Windows XP x64");
INSERT IGNORE INTO OS (Project,Value) VALUES ("CTRL","Windows XP x86");
INSERT IGNORE INTO OS (Project,Value) VALUES ("CTRL","Xen Server 6.0");
INSERT IGNORE INTO OS (Project,Value) VALUES ("CTRL","Xen Server 6.1");
INSERT IGNORE INTO OS (Project,Value) VALUES ("CTRL","Xen Server 6.2");
INSERT IGNORE INTO OS (Project,Value) VALUES ("CTRL","uEFI IA-32");
INSERT IGNORE INTO OS (Project,Value) VALUES ("CTRL","uEFI IA-64");
INSERT IGNORE INTO OS (Project,Value) VALUES ("CTRL","uEFI x64");

/* Package */
DELETE FROM Package WHERE Project = "CTRL" AND idPackage != 0;

/* Product */
DELETE FROM Product WHERE Project = "CTRL" AND idProduct != 0;
INSERT IGNORE INTO Product (Project,Value) VALUES ("CTRL","NetXtreme I");
INSERT IGNORE INTO Product (Project,Value) VALUES ("CTRL","NetXtreme C");
INSERT IGNORE INTO Product (Project,Value) VALUES ("CTRL","NetXtreme E");
INSERT IGNORE INTO Product (Project,Value) VALUES ("CTRL","Cumulus");
INSERT IGNORE INTO Product (Project,Value) VALUES ("CTRL","Whitney");

/* Releases */
DELETE FROM Releases WHERE Project = "CTRL" AND idReleases != 0;
INSERT IGNORE INTO Releases (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","4401_1.0.0");
INSERT IGNORE INTO Releases (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","4401_3.0.0");
INSERT IGNORE INTO Releases (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","4401_6.5.0");
INSERT IGNORE INTO Releases (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","4401_6.9.0");
INSERT IGNORE INTO Releases (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","4401_7.1.0");
INSERT IGNORE INTO Releases (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","4401_7.2.0");
INSERT IGNORE INTO Releases (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","4401_7.3.0");
INSERT IGNORE INTO Releases (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","BLANK");
INSERT IGNORE INTO Releases (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","NX1_14.4.0b");
INSERT IGNORE INTO Releases (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","nx1_10.0.0");
INSERT IGNORE INTO Releases (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","nx1_10.4.0");
INSERT IGNORE INTO Releases (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","nx1_10.4.0b");
INSERT IGNORE INTO Releases (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","nx1_10.4.0c");
INSERT IGNORE INTO Releases (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","nx1_10.4.0d");
INSERT IGNORE INTO Releases (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","nx1_10.7.0");
INSERT IGNORE INTO Releases (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","nx1_10.7.0b");
INSERT IGNORE INTO Releases (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","nx1_11.0.0");
INSERT IGNORE INTO Releases (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","nx1_11.0.0a");
INSERT IGNORE INTO Releases (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","nx1_11.0.0b");
INSERT IGNORE INTO Releases (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","nx1_11.4.0");
INSERT IGNORE INTO Releases (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","nx1_11.7.0");
INSERT IGNORE INTO Releases (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","nx1_11.9.0");
INSERT IGNORE INTO Releases (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","nx1_12.0.0");
INSERT IGNORE INTO Releases (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","nx1_12.2.0");
INSERT IGNORE INTO Releases (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","nx1_12.2.0a");
INSERT IGNORE INTO Releases (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","nx1_12.4.0");
INSERT IGNORE INTO Releases (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","nx1_13.2.0");
INSERT IGNORE INTO Releases (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","nx1_14.0.0");
INSERT IGNORE INTO Releases (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","nx1_14.2.0");
INSERT IGNORE INTO Releases (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","nx1_14.2.0a");
INSERT IGNORE INTO Releases (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","nx1_14.4.0");
INSERT IGNORE INTO Releases (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","nx1_14.6.0");
INSERT IGNORE INTO Releases (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","nx1_14.8.0");
INSERT IGNORE INTO Releases (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","nx1_15.0.0");
INSERT IGNORE INTO Releases (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","nx1_15.0.0a");
INSERT IGNORE INTO Releases (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","nx1_15.2.0");
INSERT IGNORE INTO Releases (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","nx1_15.2.0a");
INSERT IGNORE INTO Releases (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","nx1_15.4.0");
INSERT IGNORE INTO Releases (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","nx1_15.6.0");
INSERT IGNORE INTO Releases (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","nx1_15.6.0a");
INSERT IGNORE INTO Releases (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","nx1_16.0.0");
INSERT IGNORE INTO Releases (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","nx1_16.0.0gu");
INSERT IGNORE INTO Releases (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","nx1_16.2.0gu");
INSERT IGNORE INTO Releases (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","nx1_16.4.0");
INSERT IGNORE INTO Releases (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","nx1_16.4.0gu");
INSERT IGNORE INTO Releases (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","nx1_16.6.0");
INSERT IGNORE INTO Releases (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","nx1_16.6.0gu");
INSERT IGNORE INTO Releases (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","nx1_16.8.0");
INSERT IGNORE INTO Releases (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","nx1_16.8.0gu");
INSERT IGNORE INTO Releases (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","nx1_17.0.0");
INSERT IGNORE INTO Releases (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","nx1_17.2.0");
INSERT IGNORE INTO Releases (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","nx1_4.0.0");
INSERT IGNORE INTO Releases (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","nx1_4.1.0");
INSERT IGNORE INTO Releases (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","nx1_4.2.0");
INSERT IGNORE INTO Releases (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","nx1_5.0.0");
INSERT IGNORE INTO Releases (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","nx1_5.1.0");
INSERT IGNORE INTO Releases (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","nx1_5.1.4");
INSERT IGNORE INTO Releases (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","nx1_5.2.0");
INSERT IGNORE INTO Releases (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","nx1_5.3.0");
INSERT IGNORE INTO Releases (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","nx1_5.5.0");
INSERT IGNORE INTO Releases (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","nx1_6.0.0");
INSERT IGNORE INTO Releases (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","nx1_6.5.0");
INSERT IGNORE INTO Releases (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","nx1_6.6.0");
INSERT IGNORE INTO Releases (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","nx1_6.7.0");
INSERT IGNORE INTO Releases (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","nx1_6.8.0");
INSERT IGNORE INTO Releases (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","nx1_7.0.0");
INSERT IGNORE INTO Releases (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","nx1_7.5.0");
INSERT IGNORE INTO Releases (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","nx1_7.6.0");
INSERT IGNORE INTO Releases (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","nx1_7.7.0");
INSERT IGNORE INTO Releases (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","nx1_8.0.0");
INSERT IGNORE INTO Releases (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","nx1_8.1.0");
INSERT IGNORE INTO Releases (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","nx1_8.2.0");
INSERT IGNORE INTO Releases (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","nx1_8.3.0");
INSERT IGNORE INTO Releases (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","nx1_9.0.0");
INSERT IGNORE INTO Releases (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","nx1_9.4.0");
INSERT IGNORE INTO Releases (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","nx1_9.4.0b");
INSERT IGNORE INTO Releases (Project,Product,Customer,Value) VALUES ("CTRL","NetXtreme I","Broadcom","nx1_9.7.0");

/* Software_Component */
DELETE FROM Software_Component WHERE Project = "CTRL" AND idSoftware_Component != 0;
INSERT IGNORE INTO Software_Component (Project,Product,Value) VALUES ("CTRL","NetXtreme I","ASF Firmware");
INSERT IGNORE INTO Software_Component (Project,Product,Value) VALUES ("CTRL","NetXtreme I","ASF Installer");
INSERT IGNORE INTO Software_Component (Project,Product,Value) VALUES ("CTRL","NetXtreme I","ASF SDK");
INSERT IGNORE INTO Software_Component (Project,Product,Value) VALUES ("CTRL","NetXtreme I","ASFConfig");
INSERT IGNORE INTO Software_Component (Project,Product,Value) VALUES ("CTRL","NetXtreme I","ASFIpMon");
INSERT IGNORE INTO Software_Component (Project,Product,Value) VALUES ("CTRL","NetXtreme I","ASFIpMonLnx");
INSERT IGNORE INTO Software_Component (Project,Product,Value) VALUES ("CTRL","NetXtreme I","ASFMGTCON");
INSERT IGNORE INTO Software_Component (Project,Product,Value) VALUES ("CTRL","NetXtreme I","ASFNetMon");
INSERT IGNORE INTO Software_Component (Project,Product,Value) VALUES ("CTRL","NetXtreme I","ASFRemoteCfg-script");
INSERT IGNORE INTO Software_Component (Project,Product,Value) VALUES ("CTRL","NetXtreme I","ASFRemoteConfig");
INSERT IGNORE INTO Software_Component (Project,Product,Value) VALUES ("CTRL","NetXtreme I","ASFSilentCfg");
INSERT IGNORE INTO Software_Component (Project,Product,Value) VALUES ("CTRL","NetXtreme I","B44EDIAG");
INSERT IGNORE INTO Software_Component (Project,Product,Value) VALUES ("CTRL","NetXtreme I","B44UDIAG");
INSERT IGNORE INTO Software_Component (Project,Product,Value) VALUES ("CTRL","NetXtreme I","B57DIAG");
INSERT IGNORE INTO Software_Component (Project,Product,Value) VALUES ("CTRL","NetXtreme I","B57UDIAG");
INSERT IGNORE INTO Software_Component (Project,Product,Value) VALUES ("CTRL","NetXtreme I","B57Util");
INSERT IGNORE INTO Software_Component (Project,Product,Value) VALUES ("CTRL","NetXtreme I","B57WinDiag");
INSERT IGNORE INTO Software_Component (Project,Product,Value) VALUES ("CTRL","NetXtreme I","B57uEFIDiag");
INSERT IGNORE INTO Software_Component (Project,Product,Value) VALUES ("CTRL","NetXtreme I","BACS CLI");
INSERT IGNORE INTO Software_Component (Project,Product,Value) VALUES ("CTRL","NetXtreme I","BACS GUI");
INSERT IGNORE INTO Software_Component (Project,Product,Value) VALUES ("CTRL","NetXtreme I","BASP - Vista/Longhorn");
INSERT IGNORE INTO Software_Component (Project,Product,Value) VALUES ("CTRL","NetXtreme I","BASP Linux");
INSERT IGNORE INTO Software_Component (Project,Product,Value) VALUES ("CTRL","NetXtreme I","BASP NT");
INSERT IGNORE INTO Software_Component (Project,Product,Value) VALUES ("CTRL","NetXtreme I","BASP NW");
INSERT IGNORE INTO Software_Component (Project,Product,Value) VALUES ("CTRL","NetXtreme I","BASP NW4");
INSERT IGNORE INTO Software_Component (Project,Product,Value) VALUES ("CTRL","NetXtreme I","BASP W2K");
INSERT IGNORE INTO Software_Component (Project,Product,Value) VALUES ("CTRL","NetXtreme I","BASP W2K3");
INSERT IGNORE INTO Software_Component (Project,Product,Value) VALUES ("CTRL","NetXtreme I","BASP Whistler");
INSERT IGNORE INTO Software_Component (Project,Product,Value) VALUES ("CTRL","NetXtreme I","BASP Whistler64");
INSERT IGNORE INTO Software_Component (Project,Product,Value) VALUES ("CTRL","NetXtreme I","BLANK");
INSERT IGNORE INTO Software_Component (Project,Product,Value) VALUES ("CTRL","NetXtreme I","BMAPI");
INSERT IGNORE INTO Software_Component (Project,Product,Value) VALUES ("CTRL","NetXtreme I","BMCC");
INSERT IGNORE INTO Software_Component (Project,Product,Value) VALUES ("CTRL","NetXtreme I","BOOTP");
INSERT IGNORE INTO Software_Component (Project,Product,Value) VALUES ("CTRL","NetXtreme I","BaspSCfg");
INSERT IGNORE INTO Software_Component (Project,Product,Value) VALUES ("CTRL","NetXtreme I","Bonjour Proxy Firmware");
INSERT IGNORE INTO Software_Component (Project,Product,Value) VALUES ("CTRL","NetXtreme I","Bootcode");
INSERT IGNORE INTO Software_Component (Project,Product,Value) VALUES ("CTRL","NetXtreme I","BrcmMgmtAgent");
INSERT IGNORE INTO Software_Component (Project,Product,Value) VALUES ("CTRL","NetXtreme I","CAB32");
INSERT IGNORE INTO Software_Component (Project,Product,Value) VALUES ("CTRL","NetXtreme I","CCM");
INSERT IGNORE INTO Software_Component (Project,Product,Value) VALUES ("CTRL","NetXtreme I","CD");
INSERT IGNORE INTO Software_Component (Project,Product,Value) VALUES ("CTRL","NetXtreme I","CHKFIRM");
INSERT IGNORE INTO Software_Component (Project,Product,Value) VALUES ("CTRL","NetXtreme I","CIM/CMPI Provider");
INSERT IGNORE INTO Software_Component (Project,Product,Value) VALUES ("CTRL","NetXtreme I","CIM/WMI Provider");
INSERT IGNORE INTO Software_Component (Project,Product,Value) VALUES ("CTRL","NetXtreme I","CLP-PXE");
INSERT IGNORE INTO Software_Component (Project,Product,Value) VALUES ("CTRL","NetXtreme I","Card Reader MS");
INSERT IGNORE INTO Software_Component (Project,Product,Value) VALUES ("CTRL","NetXtreme I","Card Reader SD");
INSERT IGNORE INTO Software_Component (Project,Product,Value) VALUES ("CTRL","NetXtreme I","Card Reader XD");
INSERT IGNORE INTO Software_Component (Project,Product,Value) VALUES ("CTRL","NetXtreme I","Crash Dump");
INSERT IGNORE INTO Software_Component (Project,Product,Value) VALUES ("CTRL","NetXtreme I","DMI");
INSERT IGNORE INTO Software_Component (Project,Product,Value) VALUES ("CTRL","NetXtreme I","DUP");
INSERT IGNORE INTO Software_Component (Project,Product,Value) VALUES ("CTRL","NetXtreme I","DashMgmtCon");
INSERT IGNORE INTO Software_Component (Project,Product,Value) VALUES ("CTRL","NetXtreme I","Driver Installer");
INSERT IGNORE INTO Software_Component (Project,Product,Value) VALUES ("CTRL","NetXtreme I","EFI Diag");
INSERT IGNORE INTO Software_Component (Project,Product,Value) VALUES ("CTRL","NetXtreme I","EFI");
INSERT IGNORE INTO Software_Component (Project,Product,Value) VALUES ("CTRL","NetXtreme I","EFIUDIAG");
INSERT IGNORE INTO Software_Component (Project,Product,Value) VALUES ("CTRL","NetXtreme I","ESX Everest L2");
INSERT IGNORE INTO Software_Component (Project,Product,Value) VALUES ("CTRL","NetXtreme I","ESX TG3");
INSERT IGNORE INTO Software_Component (Project,Product,Value) VALUES ("CTRL","NetXtreme I","ESX bnx2");
INSERT IGNORE INTO Software_Component (Project,Product,Value) VALUES ("CTRL","NetXtreme I","ESX iSCSI");
INSERT IGNORE INTO Software_Component (Project,Product,Value) VALUES ("CTRL","NetXtreme I","FCoE - Linux Open-FCoE");
INSERT IGNORE INTO Software_Component (Project,Product,Value) VALUES ("CTRL","NetXtreme I","FCoE - Vmware");
INSERT IGNORE INTO Software_Component (Project,Product,Value) VALUES ("CTRL","NetXtreme I","FW Upg Util for ESX");
INSERT IGNORE INTO Software_Component (Project,Product,Value) VALUES ("CTRL","NetXtreme I","FW Upg Util for Linux");
INSERT IGNORE INTO Software_Component (Project,Product,Value) VALUES ("CTRL","NetXtreme I","FW Upg Util for Win");
INSERT IGNORE INTO Software_Component (Project,Product,Value) VALUES ("CTRL","NetXtreme I","FreeBSD");
INSERT IGNORE INTO Software_Component (Project,Product,Value) VALUES ("CTRL","NetXtreme I","IPMI");
INSERT IGNORE INTO Software_Component (Project,Product,Value) VALUES ("CTRL","NetXtreme I","LSI Diagnostic");
INSERT IGNORE INTO Software_Component (Project,Product,Value) VALUES ("CTRL","NetXtreme I","Linux BCM4400");
INSERT IGNORE INTO Software_Component (Project,Product,Value) VALUES ("CTRL","NetXtreme I","Linux BCM5700");
INSERT IGNORE INTO Software_Component (Project,Product,Value) VALUES ("CTRL","NetXtreme I","Linux Diag");
INSERT IGNORE INTO Software_Component (Project,Product,Value) VALUES ("CTRL","NetXtreme I","Linux TG3");
INSERT IGNORE INTO Software_Component (Project,Product,Value) VALUES ("CTRL","NetXtreme I","Linux TG3SD");
INSERT IGNORE INTO Software_Component (Project,Product,Value) VALUES ("CTRL","NetXtreme I","Mgmt Pass-through Firmware");
INSERT IGNORE INTO Software_Component (Project,Product,Value) VALUES ("CTRL","NetXtreme I","MgmtApps Installer");
INSERT IGNORE INTO Software_Component (Project,Product,Value) VALUES ("CTRL","NetXtreme I","Modem");
INSERT IGNORE INTO Software_Component (Project,Product,Value) VALUES ("CTRL","NetXtreme I","NA");
INSERT IGNORE INTO Software_Component (Project,Product,Value) VALUES ("CTRL","NetXtreme I","NDIS 2");
INSERT IGNORE INTO Software_Component (Project,Product,Value) VALUES ("CTRL","NetXtreme I","NDIS 3");
INSERT IGNORE INTO Software_Component (Project,Product,Value) VALUES ("CTRL","NetXtreme I","NDIS 4");
INSERT IGNORE INTO Software_Component (Project,Product,Value) VALUES ("CTRL","NetXtreme I","NDIS 5");
INSERT IGNORE INTO Software_Component (Project,Product,Value) VALUES ("CTRL","NetXtreme I","NDIS 5.1 AMD64");
INSERT IGNORE INTO Software_Component (Project,Product,Value) VALUES ("CTRL","NetXtreme I","NDIS 5.1");
INSERT IGNORE INTO Software_Component (Project,Product,Value) VALUES ("CTRL","NetXtreme I","NDIS 5.2");
INSERT IGNORE INTO Software_Component (Project,Product,Value) VALUES ("CTRL","NetXtreme I","NDIS 6.0");
INSERT IGNORE INTO Software_Component (Project,Product,Value) VALUES ("CTRL","NetXtreme I","NDIS Monolithic");
INSERT IGNORE INTO Software_Component (Project,Product,Value) VALUES ("CTRL","NetXtreme I","Netware");
INSERT IGNORE INTO Software_Component (Project,Product,Value) VALUES ("CTRL","NetXtreme I","ODI 16");
INSERT IGNORE INTO Software_Component (Project,Product,Value) VALUES ("CTRL","NetXtreme I","Online Diagnostic");
INSERT IGNORE INTO Software_Component (Project,Product,Value) VALUES ("CTRL","NetXtreme I","PXE");
INSERT IGNORE INTO Software_Component (Project,Product,Value) VALUES ("CTRL","NetXtreme I","Packaging - Citrix XenServer");
INSERT IGNORE INTO Software_Component (Project,Product,Value) VALUES ("CTRL","NetXtreme I","Packet Driver");
INSERT IGNORE INTO Software_Component (Project,Product,Value) VALUES ("CTRL","NetXtreme I","RPL");
INSERT IGNORE INTO Software_Component (Project,Product,Value) VALUES ("CTRL","NetXtreme I","Released CD");
INSERT IGNORE INTO Software_Component (Project,Product,Value) VALUES ("CTRL","NetXtreme I","SCO Core Driver");
INSERT IGNORE INTO Software_Component (Project,Product,Value) VALUES ("CTRL","NetXtreme I","SNMP Agent");
INSERT IGNORE INTO Software_Component (Project,Product,Value) VALUES ("CTRL","NetXtreme I","SNMP NW");
INSERT IGNORE INTO Software_Component (Project,Product,Value) VALUES ("CTRL","NetXtreme I","Solaris Driver");
INSERT IGNORE INTO Software_Component (Project,Product,Value) VALUES ("CTRL","NetXtreme I","TPM Diag");
INSERT IGNORE INTO Software_Component (Project,Product,Value) VALUES ("CTRL","NetXtreme I","TPM Firmware");
INSERT IGNORE INTO Software_Component (Project,Product,Value) VALUES ("CTRL","NetXtreme I","TPM Stack");
INSERT IGNORE INTO Software_Component (Project,Product,Value) VALUES ("CTRL","NetXtreme I","TPM");
INSERT IGNORE INTO Software_Component (Project,Product,Value) VALUES ("CTRL","NetXtreme I","TruManage SDK");
INSERT IGNORE INTO Software_Component (Project,Product,Value) VALUES ("CTRL","NetXtreme I","TruManage WMI Config Script");
INSERT IGNORE INTO Software_Component (Project,Product,Value) VALUES ("CTRL","NetXtreme I","TruManage-Client Firmware");
INSERT IGNORE INTO Software_Component (Project,Product,Value) VALUES ("CTRL","NetXtreme I","TruManage-Server Firmware");
INSERT IGNORE INTO Software_Component (Project,Product,Value) VALUES ("CTRL","NetXtreme I","UMP Firmware");
INSERT IGNORE INTO Software_Component (Project,Product,Value) VALUES ("CTRL","NetXtreme I","UNDI 32/64");
INSERT IGNORE INTO Software_Component (Project,Product,Value) VALUES ("CTRL","NetXtreme I","Unixware 7");
INSERT IGNORE INTO Software_Component (Project,Product,Value) VALUES ("CTRL","NetXtreme I","Unixware Core Driver");
INSERT IGNORE INTO Software_Component (Project,Product,Value) VALUES ("CTRL","NetXtreme I","Windows Diagnostic");
INSERT IGNORE INTO Software_Component (Project,Product,Value) VALUES ("CTRL","NetXtreme I","b44");
INSERT IGNORE INTO Software_Component (Project,Product,Value) VALUES ("CTRL","NetXtreme I","b57ldiag-v2");
INSERT IGNORE INTO Software_Component (Project,Product,Value) VALUES ("CTRL","NetXtreme I","b57wdiag");
INSERT IGNORE INTO Software_Component (Project,Product,Value) VALUES ("CTRL","NetXtreme I","iSCSI Boot");
INSERT IGNORE INTO Software_Component (Project,Product,Value) VALUES ("CTRL","NetXtreme I","iSCSI Initiator");
INSERT IGNORE INTO Software_Component (Project,Product,Value) VALUES ("CTRL","NetXtreme I","uIP");

/* Target_Branch */
DELETE FROM Target_Branch WHERE Project = "CTRL" AND idTarget_Branch != 0;

