INSERT IGNORE INTO Product (Project, Value) VALUES ("CS", "Client Security");

INSERT IGNORE INTO Customer (Project, Product, Value) VALUES ("CS", "Client Security", "Broadcom");

INSERT IGNORE INTO Customer (Project, Product, Value) VALUES ("CS", "Client Security", "Compal Electronics");
INSERT IGNORE INTO Customer (Project, Product, Value) VALUES ("CS", "Client Security", "Dell");
INSERT IGNORE INTO Customer (Project, Product, Value) VALUES ("CS", "Client Security", "Wave");



INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CS", "Client Security", "Broadcom", "0.0.5");


INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CS", "Client Security", "Broadcom", "CSS-0.0.5");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CS", "Client Security", "Broadcom", "CSS-0.1.1");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CS", "Client Security", "Broadcom", "CSS-0.1.10");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CS", "Client Security", "Broadcom", "CSS-0.1.2");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CS", "Client Security", "Broadcom", "CSS-0.1.3");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CS", "Client Security", "Broadcom", "CSS-0.1.4");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CS", "Client Security", "Broadcom", "CSS-0.1.5");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CS", "Client Security", "Broadcom", "CSS-0.1.6");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CS", "Client Security", "Broadcom", "CSS-0.1.7");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CS", "Client Security", "Broadcom", "CSS-0.1.8");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CS", "Client Security", "Broadcom", "CSS-0.1.9");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CS", "Client Security", "Broadcom", "CSS-0.2.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CS", "Client Security", "Broadcom", "CSS-0.2.1");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CS", "Client Security", "Broadcom", "CSS-0.2.2");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CS", "Client Security", "Broadcom", "CSS-0.2.3");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CS", "Client Security", "Broadcom", "CSS-0.2.4");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CS", "Client Security", "Broadcom", "CSS-0.3.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CS", "Client Security", "Broadcom", "CSS-0.3.1");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CS", "Client Security", "Broadcom", "CSS-0.3.2");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CS", "Client Security", "Broadcom", "CSS-0.3.3");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CS", "Client Security", "Broadcom", "CSS-0.3.4");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CS", "Client Security", "Broadcom", "CSS-0.3.5");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CS", "Client Security", "Broadcom", "CSS-0.4.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CS", "Client Security", "Broadcom", "CSS-0.4.1");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CS", "Client Security", "Broadcom", "CSS-0.4.2");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CS", "Client Security", "Broadcom", "CSS-0.5.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CS", "Client Security", "Broadcom", "CSS-0.6.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CS", "Client Security", "Broadcom", "CSS-0.6.1");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CS", "Client Security", "Broadcom", "CSS-0.7.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CS", "Client Security", "Broadcom", "CSS-0.8.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CS", "Client Security", "Broadcom", "CSS-0.9.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CS", "Client Security", "Broadcom", "CSS-1.0.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CS", "Client Security", "Broadcom", "CSS-1.0.1");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CS", "Client Security", "Broadcom", "CSS-1.0.2");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CS", "Client Security", "Broadcom", "CSS-1.0.3");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CS", "Client Security", "Broadcom", "CSS-1.0.4");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CS", "Client Security", "Broadcom", "CSS-1.0.5");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CS", "Client Security", "Broadcom", "CSS-1.0.6");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CS", "Client Security", "Broadcom", "CSS-1.0.7");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CS", "Client Security", "Broadcom", "CSS-1.0.8");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CS", "Client Security", "Broadcom", "CSS-1.0.9");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CS", "Client Security", "Broadcom", "CSS-1.1.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CS", "Client Security", "Broadcom", "CSS-1.1.1");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CS", "Client Security", "Broadcom", "CSS-1.1.2");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CS", "Client Security", "Broadcom", "CSS-1.1.4");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CS", "Client Security", "Broadcom", "CSS-1.1.5");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CS", "Client Security", "Broadcom", "CSS-1.1.6");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CS", "Client Security", "Broadcom", "CSS-1.1.7");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CS", "Client Security", "Broadcom", "CSS-1.10.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CS", "Client Security", "Broadcom", "CSS-1.2.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CS", "Client Security", "Broadcom", "CSS-1.2.2");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CS", "Client Security", "Broadcom", "CSS-1.2.3");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CS", "Client Security", "Broadcom", "CSS-1.2.4");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CS", "Client Security", "Broadcom", "CSS-1.2.5");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CS", "Client Security", "Broadcom", "CSS-1.2.6");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CS", "Client Security", "Broadcom", "CSS-1.2.7");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CS", "Client Security", "Broadcom", "CSS-1.3.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CS", "Client Security", "Broadcom", "CSS-1.3.5");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CS", "Client Security", "Broadcom", "CSS-1.4.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CS", "Client Security", "Broadcom", "CSS-1.5.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CS", "Client Security", "Broadcom", "CSS-1.5.3");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CS", "Client Security", "Broadcom", "CSS-1.5.4");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CS", "Client Security", "Broadcom", "CSS-1.5.7");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CS", "Client Security", "Broadcom", "CSS-1.5.9");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CS", "Client Security", "Broadcom", "CSS-1.6.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CS", "Client Security", "Broadcom", "CSS-2.0.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CS", "Client Security", "Broadcom", "CSS-2.1.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CS", "Client Security", "Broadcom", "CSS-2.2.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CS", "Client Security", "Broadcom", "CSS-2.2.2");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CS", "Client Security", "Broadcom", "CSS-2.3.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CS", "Client Security", "Broadcom", "CSS-2.5.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CS", "Client Security", "Broadcom", "CSS-3.0.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CS", "Client Security", "Broadcom", "CSS-4.0.1");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CS", "Client Security", "Broadcom", "NOT_IMPORTED");



INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CS", "Client Security", "Broadcom", "5880_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CS", "Client Security", "Broadcom", "5880_B0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CS", "Client Security", "Broadcom", "5880_B1");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CS", "Client Security", "Broadcom", "5880_C0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CS", "Client Security", "Broadcom", "5881_C0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CS", "Client Security", "Broadcom", "5882_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CS", "Client Security", "Broadcom", "5882_B0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CS", "Client Security", "Broadcom", "5882_B1");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CS", "Client Security", "Broadcom", "5882_C0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CS", "Client Security", "Broadcom", "5892_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CS", "Client Security", "Broadcom", "5892_B0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CS", "Client Security", "Broadcom", "5892_B1");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CS", "Client Security", "Broadcom", "5892_C0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CS", "Client Security", "Broadcom", "ALL");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CS", "Client Security", "Broadcom", "NA");


INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CS", "Client Security", "BIO-API");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CS", "Client Security", "BIP");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CS", "Client Security", "Backup and Restore");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CS", "Client Security", "CV-API");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CS", "Client Security", "CV-USB-driver");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CS", "Client Security", "DCPSM");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CS", "Client Security", "FMA");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CS", "Client Security", "FW-Upgrade");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CS", "Client Security", "Fingerprint");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CS", "Client Security", "Host-Services");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CS", "Client Security", "Installer");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CS", "Client Security", "NFC");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CS", "Client Security", "NOT_IMPORTED");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CS", "Client Security", "PBA");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CS", "Client Security", "PC-SC-Contact-less");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CS", "Client Security", "PC-SC-Contacted");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CS", "Client Security", "Power Management");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CS", "Client Security", "SBL");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CS", "Client Security", "Stability");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CS", "Client Security", "TPM");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CS", "Client Security", "USH-USB-Device");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CS", "Client Security", "USH-USB-Host");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CS", "Client Security", "USHDIAG");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CS", "Client Security", "WHQL");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CS", "Client Security", "WMI-API");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CS", "Client Security", "WinPE");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CS", "Client Security", "Documentation Installer");
