
INSERT IGNORE INTO Product (Project, Value) VALUES ("CTRL", "Controller");


INSERT IGNORE INTO Customer (Project, Product, Value) VALUES ("CTRL", "Controller", "Broadcom");


INSERT IGNORE INTO Customer (Project, Product, Value) VALUES ("CTRL", "Controller", "Acer");
INSERT IGNORE INTO Customer (Project, Product, Value) VALUES ("CTRL", "Controller", "AMD");
INSERT IGNORE INTO Customer (Project, Product, Value) VALUES ("CTRL", "Controller", "Apple");
INSERT IGNORE INTO Customer (Project, Product, Value) VALUES ("CTRL", "Controller", "Broadcom");
INSERT IGNORE INTO Customer (Project, Product, Value) VALUES ("CTRL", "Controller", "Dell Desktop");
INSERT IGNORE INTO Customer (Project, Product, Value) VALUES ("CTRL", "Controller", "Dell Mobile");
INSERT IGNORE INTO Customer (Project, Product, Value) VALUES ("CTRL", "Controller", "Dell Server");
INSERT IGNORE INTO Customer (Project, Product, Value) VALUES ("CTRL", "Controller", "EMC");
INSERT IGNORE INTO Customer (Project, Product, Value) VALUES ("CTRL", "Controller", "Foxconn");
INSERT IGNORE INTO Customer (Project, Product, Value) VALUES ("CTRL", "Controller", "Fujitsu");
INSERT IGNORE INTO Customer (Project, Product, Value) VALUES ("CTRL", "Controller", "Hitachi");
INSERT IGNORE INTO Customer (Project, Product, Value) VALUES ("CTRL", "Controller", "HP Desktop");
INSERT IGNORE INTO Customer (Project, Product, Value) VALUES ("CTRL", "Controller", "HP Mobile");
INSERT IGNORE INTO Customer (Project, Product, Value) VALUES ("CTRL", "Controller", "HP Server");
INSERT IGNORE INTO Customer (Project, Product, Value) VALUES ("CTRL", "Controller", "HP Workstation");
INSERT IGNORE INTO Customer (Project, Product, Value) VALUES ("CTRL", "Controller", "HuaWei");
INSERT IGNORE INTO Customer (Project, Product, Value) VALUES ("CTRL", "Controller", "IBM Desktop");
INSERT IGNORE INTO Customer (Project, Product, Value) VALUES ("CTRL", "Controller", "Inventec");
INSERT IGNORE INTO Customer (Project, Product, Value) VALUES ("CTRL", "Controller", "Lenovo Desktop");
INSERT IGNORE INTO Customer (Project, Product, Value) VALUES ("CTRL", "Controller", "Lenovo Mobile");
INSERT IGNORE INTO Customer (Project, Product, Value) VALUES ("CTRL", "Controller", "Lenovo Server");
INSERT IGNORE INTO Customer (Project, Product, Value) VALUES ("CTRL", "Controller", "Microsoft");
INSERT IGNORE INTO Customer (Project, Product, Value) VALUES ("CTRL", "Controller", "Mitec");
INSERT IGNORE INTO Customer (Project, Product, Value) VALUES ("CTRL", "Controller", "MSI");
INSERT IGNORE INTO Customer (Project, Product, Value) VALUES ("CTRL", "Controller", "NEC");
INSERT IGNORE INTO Customer (Project, Product, Value) VALUES ("CTRL", "Controller", "NOT_IMPORTED");
INSERT IGNORE INTO Customer (Project, Product, Value) VALUES ("CTRL", "Controller", "Quanta");
INSERT IGNORE INTO Customer (Project, Product, Value) VALUES ("CTRL", "Controller", "Vmware");
INSERT IGNORE INTO Customer (Project, Product, Value) VALUES ("CTRL", "Controller", "Wistron");



INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "4401_6.5.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "4401_6.9.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "4401_7.1.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "4401_7.2.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "4401_7.3.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "NOT_IMPORTED");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "nx1_10.0.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "nx1_10.4.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "nx1_10.4.0b");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "nx1_10.4.0c");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "nx1_10.4.0d");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "nx1_10.7.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "nx1_10.7.0b");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "nx1_11.0.0a");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "nx1_11.0.0b");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "nx1_11.4.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "nx1_11.7.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "nx1_11.9.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "nx1_12.0.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "nx1_12.2.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "nx1_12.2.0a");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "nx1_12.4.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "nx1_13.2.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "nx1_14.0.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "nx1_14.2.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "nx1_14.4.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "NX1_14.4.0b");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "nx1_14.6.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "nx1_14.8.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "nx1_15.0.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "nx1_15.0.0a");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "nx1_15.2.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "nx1_15.2.0a");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "nx1_15.4.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "nx1_15.6.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "nx1_15.6.0a");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "nx1_16.0.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "nx1_16.0.0gu");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "nx1_16.2.0gu");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "nx1_16.4.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "nx1_16.4.0gu");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "nx1_16.6.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "nx1_16.6.0gu");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "nx1_16.8.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "nx1_16.8.0gu");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "nx1_17.0.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "nx1_4.0.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "nx1_4.1.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "nx1_4.2.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "nx1_5.0.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "nx1_5.1.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "nx1_5.1.4");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "nx1_5.2.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "nx1_5.3.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "nx1_5.5.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "nx1_6.0.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "nx1_6.5.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "nx1_6.6.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "nx1_6.7.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "nx1_6.8.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "nx1_7.0.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "nx1_7.5.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "nx1_7.6.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "nx1_7.7.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "nx1_7.9.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "nx1_8.0.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "nx1_8.1.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "nx1_8.2.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "nx1_8.3.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "nx1_9.0.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "nx1_9.4.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "nx1_9.4.0b");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "nx1_9.7.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "nx2_2.0.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "nx2_2.1.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "nx2_2.5.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "nx2_2.6.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "nx2_2.8.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "nx2_2.9.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "nx2_3.0.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "nx2_3.2.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "nx2_3.4.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "nx2_3.5.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "nx2_3.7.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "nx2_4.0.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "nx2_4.0.0e");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "nx2_4.1.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "nx2_4.4.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "nx2_4.5.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "nx2_4.6.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "nx2_4.6.0+");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "nx2_4.6.0b");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "nx2_4.8.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "nx2_5.0.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "nx2_5.0.0a");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "nx2_5.2.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "nx2_5.2.0a");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "nx2_6.0.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "nx2_6.2.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "nx2_6.2.0a");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "nx2_6.4.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "nx2_7.0.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "nx2_7.0.0a");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "nx2_7.10.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "nx2_7.10.0a");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "nx2_7.10.0c");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "nx2_7.12.0a");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "nx2_7.2.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "nx2_7.2.0a");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "nx2_7.4.0");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "nx2_7.4.0gu");
INSERT IGNORE INTO Releases (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "nx2_8.0.0");


INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM94401 v1.0");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM94401 v2.0");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM94401 v3.0");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM94401A10 v3.0 revA0");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM94401A10 v3.0 revA1");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM94401A10 v3.0 revA2");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM94401A10 v4.0 revA1");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM94401A10 v5.0 revA0");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM94401A20F v0.0 revA0");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM94401ET0101 v0.0 revP1");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM94401ET0101 v0.0 revP3");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM94401T41 v0.0");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM95708A0804F v0.0 revB");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM95709A0907G");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM95709A0930G");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM95709SA0930G");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM95709ST0903G v1.0 revP3");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM95709T0903 v1.0 revP2");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM957101T0100G");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM95714 v0.02 revB");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM95714S v0.01 revA");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM95714ST144 v0.0 revP4");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM95714T143 v1.0 revP1");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM95714T143 v1.0 revP3");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM95715A155F v0.0 revP1");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM95715ST154 v1.0 revP2");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM95717T1700G revP4");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM95718 T1800G revP6");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM95718A1805G");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM95718T1800G revP4");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM95719A1904G");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM95719A1904G_C");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM95719A1904G_D");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM95719A1904G_H");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM95719A1904G_I");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM95719A1905G");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM95719T1900G revP3");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM95719T900G revP5");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM95720A2003G");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM95720A2003G_C");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM95720A2003G_D");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM95720A2003G_H");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM95720A2003G_I");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM95720T2000G revP2");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM95721T210 v2.0 revA1");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM95721T210 v3.0 revA1");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM95721T2101 v0.0 revP2");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM95722T2200G v0.0 revP3");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM95724T2400G revP5");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM95725T2500G");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM95727T2700G rev01");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM95750T503 v0.0 revA1");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM95750T503 v0.0 revA2");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM95750T503 v0.0 revA5");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM95751A519 v1.0 revA0");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM95751FA519 v0.0 revA0");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM95751MT515 v0.0 revA0");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM95751T5101 v0.0 revP3");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM95751T512 v2.0 rev000");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM95751T512 v2.0 revA3");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM95751T512 v3.0 revA2");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM95751T512 v4.0 revA1");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM95751T512 v4.0 revA2");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM95752T5200 v0.0 revP5");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM95752T5204 v0.0 revP1");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM95753T5301 v0.0 revP1");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM95754MT5400 revP3");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM95754T5400 v0.0 revP1");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM95754T5404 v0.0 revP3");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM95754T5404 v2.0 revP1");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM95755MT5506 v0.0 revP1");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM95755T5501 v2.0 revP1");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM95756MET5600F v0.0 revP1");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM95761A6110G");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM95761A6110G revP4");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM95761A6110G v0.0 revP2");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM95761ET6103G v0.0 revP3");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM95761T6100G v0.0 revP7");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM95762T6200G");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM95764MT6401G v0.0 revP5");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM957710A1021G");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM957712A1202G");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM957712A1213G");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM957712A1288");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM957760T6000G v0.0 revP3");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM957760T6000G v0.0 revP5");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM957761T6100G revP1");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM957762T6200G revP1");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM957765T6500G");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM957765XT6500G revP2");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM957765XT6500G revP4");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM957766T6600G revP1");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM957766T6600G revP4");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM957767T6700G");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM957780T8000G v0.0 revP4");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM957780T8000G v0.0 revP5");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM957781T8100G revP1");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM957782T8200G revP1");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM957785T8500G");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM957785T8500G revP2");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM957785XT8500G");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM957785XT8500G revP2");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM957785XT8500G revP4");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM957785XT8500G revP5");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM957786XT8600G revP1");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM957787T8700G");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM957795T9500G revP2");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM957800A0006G");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM957800T0000G");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM957810A1006G");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM957810A1006G_D");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM957810A1007G");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM957810A1008G");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM957810A1008G_D");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM957810A1008G_I");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM957810T1000G");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM95782A50-H v0.0 revA1");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM95782A50-H v1.0 revA0");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM95782A50-H v1.0 revA1");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM95782A50-H v2.0 revA1");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM9578401g v0.0 revP4");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM957840T4000G");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM95786T8600 v0.0 revP1");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM95787MT8704 v2.0 revP2");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM95787T8701 v0.0 revP3");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM95788A50 v1.0 revA2");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM95901T57 v0.0 rev000");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM95906MT0604F v0.0 revP3");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM95906T0600 v0.0 revP2");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM95906T0600F v0.0 revP3");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM9751T5101 v0.0 revP1");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "BCM9751T5101 v0.0 revP2");
INSERT IGNORE INTO Hardware_Board_Revision (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "NOT_IMPORTED");


INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "4401");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5714");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5715");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5716");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5717");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5718");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5719");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5720");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5721");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5722");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5723");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5725");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5727");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5750");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5751");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5752");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5753");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5754");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5755");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5760");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5761");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5762");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5782");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5785");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5786");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5787");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5788");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5789");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5906");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "57340");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "57760");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "57762");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "57765");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "57780");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "57785");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "57791");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "57800");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "4401_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "4401_A1");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "4401_A2");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "4401_B0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "4401_B1");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "4401_E0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5714_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5714_A1");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5714_A2");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5714_A3");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5714_A4");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5714_B0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5714S");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5714S_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5714S_A1");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5714S_A2");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5714S_A3");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5715_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5715_A1");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5715_A2");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5715_A3");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5715_B0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5715_B1");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5715_C0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5715S");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5715S_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5715S_A1");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5715S_A2");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5715S_A3");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5715S_B0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5716_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5716_A1");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5716_C0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5716_C1");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5717_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5717_A1");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5717_B0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5717_B1");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5717_B2");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5717_C0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5717S");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5717S_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5718_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5718_A1");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5718_B0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5718_C0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5718_E0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5719_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5719_A1");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5719_A2");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5719_A5");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5719_B0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5719_E0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5720_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5720_A1");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5720_B0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5720_B1");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5720_C0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5721_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5721_A1");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5721_A2");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5721_A3");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5721_A4");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5721_A5");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5721_B0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5721_B1");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5721_B2");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5721_C0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5721_C1");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5722_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5722_A1");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5722_A2");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5722_B0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5722_B1");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5722_C0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5722_C1");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5723_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5723_A1");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5723_B0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5723_B1");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5724_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5725_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5725_A1");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5725_B0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5727_B0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5750_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5750_A1");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5750_A3");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5750_A4");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5751_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5751_A1");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5751_A2");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5751_A3");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5751_A4");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5751_A5");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5751_B0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5751_B1");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5751_B2");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5751_C0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5751_C1");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5751_C2");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5751F");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5751F_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5751F_A1");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5751F_B0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5751F_B1");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5751F_C0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5751F_C1");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5751M");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5751M_A1");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5751M_A3");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5751M_A4");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5751M_B0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5751M_B1");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5751M_C0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5751M_C1");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5752_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5752_A1");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5752_A2");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5752_A3");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5752_B0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5752_B1");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5752M");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5752M_A2");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5753_A1");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5753_A2");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5753_A4");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5753_B1");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5753_B3");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5753_C0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5753_C1");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5753M");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5753M_A1");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5753M_A2");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5753M_C1");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5753M_C2");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5754_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5754_A1");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5754_A2");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5754_B0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5754M_A2");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5755_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5755_A1");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5755_A2");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5755M");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5755M_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5755M_A1");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5755M_A2");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5756ME");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5756ME_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5756ME_A1");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5756ME_A2");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5756ME_B0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5760_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5760_A1");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5760_B0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5761_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5761_A1");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5761_A2");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5761_B0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5761_B1");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5761_B2");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5761E");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5761E_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5761E_A2");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5761E_B0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5761M");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5761M_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5761M_A2");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5761M_B0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5761M_B1");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5761S_B0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5762_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5762_A1");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5762_B0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5764M");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5764M_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5764M_A1");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5764M_B0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5764M_B1");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "57760_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "57760_A1");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "57760_A2");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "57760_B0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "57761_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "57761_A1");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "57761_B0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "57762_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "57762_A1");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "57762_B0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "57762_C0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "57765_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "57765_A1");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "57765_B0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "57765_E0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "57766_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "57766_A1");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "57766_B0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "57766_C0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "57767_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "57767_A1");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "57767_B0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "57780_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "57780_A1");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "57780_B0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "57781_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "57781_A1");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "57781_B0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "57782_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "57782_A1");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "57785_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "57785_A1");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "57785_B0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "57785_B1");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "57785_E0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "57786x_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "57786x_A1");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "57786x_B0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "57786x_C0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "57787_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "57787_B0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "57788_A1");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "57788_B0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "57790_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "57790_A1");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "57790_A2");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "57795_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "57800_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "57800_A1");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "57800_B0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "57800_B1");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "57800_E0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5782_A1");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5782_A2");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5782_A3");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5784M");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5784M_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5784M_A1");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5784M_A2");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5784M_B0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5785_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5785_A1");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5785_B0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5785_B1");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5785_B2");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5786_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5786_A1");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5786_A2");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5786_A3");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5787_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5787_A1");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5787_A2");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5787F_A2");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5787M");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5787M_A1");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5787M_A2");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5787M_A4");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5787M_B0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5788_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5788_A1");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5788_A2");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5788_A3");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5788_A5");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5788_B0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5789_A2");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5789_B0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5789_B1");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5789_C0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5789_C1");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5901_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5901_A1");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5901_A3");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5903M_C2");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5906_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5906_A1");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5906_A2");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5906M");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5906M_A0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5906M_A1");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5906M_A2");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5906M_B0");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "5906M_B2");
INSERT IGNORE INTO Chip (Project, Product, Customer, Value) VALUES ("CTRL", "Controller", "Broadcom", "NOT_IMPORTED");


INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "ASF Firmware");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "ASF Installer");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "ASF SDK");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "ASFConfig");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "ASFIpMon");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "ASFIpMonLnx");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "ASFMGTCON");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "ASFNetMon");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "ASFRemoteCfg-script");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "ASFRemoteConfig");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "ASFSilentCfg");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "b44");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "B44EDIAG");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "B44UDIAG");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "B57DIAG");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "b57ldiag-v2");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "B57UDIAG");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "B57uEFIDiag");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "B57Util");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "b57wdiag");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "B57WinDiag");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "BACS CLI");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "BACS GUI");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "BASP - Vista/Longhorn");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "BASP Linux");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "BASP NT");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "BASP NW");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "BASP NW4");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "BASP W2K");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "BASP W2K3");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "BASP Whistler");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "BASP Whistler64");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "BaspSCfg");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "BMAPI");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "BMCC");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "Bonjour Proxy Firmware");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "Bootcode");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "BOOTP");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "BrcmMgmtAgent");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "BXDIAG");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "CAB32");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "Card Reader MS");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "Card Reader SD");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "Card Reader XD");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "CCM");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "CD");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "CDiag");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "CHKFIRM");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "CIM/CMPI Provider");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "CIM/WMI Provider");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "CLP-PXE");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "Crash Dump");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "DashMgmtCon");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "DMI");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "Driver Installer");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "DUP");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "edebug");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "EDiag");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "EFI");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "EFI Diag");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "EFIUDIAG");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "eLink");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "ESX bnx2");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "ESX Everest L2");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "ESX iSCSI");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "ESX TG3");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "FCoE - Boot");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "FCoE - Linux Open-FCoE");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "FCoE – Solaris");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "FCoE - Vmware");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "FCoE - Windows Storport");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "FreeBSD");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "FTSK");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "FW Upg Util for ESX");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "FW Upg Util for Linux");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "FW Upg Util for Win");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "IPMI");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "iSCSI Boot");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "iSCSI HBA - Linux");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "iSCSI HBA - Windows");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "iSCSI HBA - Windows (BRCM)");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "iSCSI HBA - Windows (HP)");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "iSCSI Initiator");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "Linux BCM4400");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "Linux BCM5700");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "Linux bnx2");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "Linux Diag");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "Linux Everest L2");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "Linux TG3");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "Linux TG3SD");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "LSI Diagnostic");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "MFW");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "Mgmt Pass-through Firmware");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "MgmtApps Installer");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "Modem");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "NA");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "NDIS 2");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "NDIS 3");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "NDIS 4");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "NDIS 5");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "NDIS 5.1");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "NDIS 5.1 AMD64");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "NDIS 5.2");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "NDIS 6.0");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "NDIS Monolithic");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "Netware");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "NOT_IMPORTED");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "ODI 16");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "Online Diagnostic");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "Packaging – Citrix XenServer");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "Packaging – Linux-NX2");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "Packet Driver");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "PXE");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "Released CD");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "RPL");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "SATA-Linux");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "SATA-MSFT");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "SCO Core Driver");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "SNMP Agent");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "SNMP NW");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "Solaris Driver");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "SQA's Test Database");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "SSL-Linux");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "SSL-W2K");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "SSL-WinDiag");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "TPM");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "TPM Diag");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "TPM Firmware");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "TPM Stack");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "TruManage SDK");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "TruManage Web GUI");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "TruManage WMI Config Script");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "TruManage-Client Firmware");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "TruManage-Server Firmware");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "UEDiag");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "uIP");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "UMP Firmware");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "UNDI 32/64");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "Unixware 7");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "Unixware Core Driver");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "UXDiag");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "VBD");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "VDIAG");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "Windows Diagnostic");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "WSD - DRVR");
INSERT IGNORE INTO Software_Component (Project, Product, Value) VALUES ("CTRL", "Controller", "XDiag");



INSERT IGNORE INTO OS (Project, Value) VALUES ("CTRL", "DOS");
INSERT IGNORE INTO OS (Project, Value) VALUES ("CTRL", "Mac OS X Snow Leopard");
INSERT IGNORE INTO OS (Project, Value) VALUES ("CTRL", "NOT_IMPORTED");
INSERT IGNORE INTO OS (Project, Value) VALUES ("CTRL", "Red Hat EL 5.10");
INSERT IGNORE INTO OS (Project, Value) VALUES ("CTRL", "Red Hat EL 5.11");
INSERT IGNORE INTO OS (Project, Value) VALUES ("CTRL", "Red Hat EL 5.5");
INSERT IGNORE INTO OS (Project, Value) VALUES ("CTRL", "Red Hat EL 5.7");
INSERT IGNORE INTO OS (Project, Value) VALUES ("CTRL", "Red Hat EL 5.8");
INSERT IGNORE INTO OS (Project, Value) VALUES ("CTRL", "Red Hat EL 5.9");
INSERT IGNORE INTO OS (Project, Value) VALUES ("CTRL", "Red Hat EL 6.0");
INSERT IGNORE INTO OS (Project, Value) VALUES ("CTRL", "Red Hat EL 6.1");
INSERT IGNORE INTO OS (Project, Value) VALUES ("CTRL", "Red Hat EL 6.2");
INSERT IGNORE INTO OS (Project, Value) VALUES ("CTRL", "Red Hat EL 6.3");
INSERT IGNORE INTO OS (Project, Value) VALUES ("CTRL", "Red Hat EL 6.4");
INSERT IGNORE INTO OS (Project, Value) VALUES ("CTRL", "Red Hat EL 6.5");
INSERT IGNORE INTO OS (Project, Value) VALUES ("CTRL", "Red Hat EL 7.0");
INSERT IGNORE INTO OS (Project, Value) VALUES ("CTRL", "Solaris 10");
INSERT IGNORE INTO OS (Project, Value) VALUES ("CTRL", "Solaris 11");
INSERT IGNORE INTO OS (Project, Value) VALUES ("CTRL", "Solaris 11 U1");
INSERT IGNORE INTO OS (Project, Value) VALUES ("CTRL", "SUSE Linux ES 10.3");
INSERT IGNORE INTO OS (Project, Value) VALUES ("CTRL", "SUSE Linux ES 10.4");
INSERT IGNORE INTO OS (Project, Value) VALUES ("CTRL", "SUSE Linux ES 11.0");
INSERT IGNORE INTO OS (Project, Value) VALUES ("CTRL", "SUSE Linux ES 11.1");
INSERT IGNORE INTO OS (Project, Value) VALUES ("CTRL", "SUSE Linux ES 11.2");
INSERT IGNORE INTO OS (Project, Value) VALUES ("CTRL", "SUSE Linux ES 11.3");
INSERT IGNORE INTO OS (Project, Value) VALUES ("CTRL", "SUSE Linux ES 12.0");
INSERT IGNORE INTO OS (Project, Value) VALUES ("CTRL", "uEFI IA-32");
INSERT IGNORE INTO OS (Project, Value) VALUES ("CTRL", "uEFI IA-64");
INSERT IGNORE INTO OS (Project, Value) VALUES ("CTRL", "uEFI x64");
INSERT IGNORE INTO OS (Project, Value) VALUES ("CTRL", "VMware ESX 4.0");
INSERT IGNORE INTO OS (Project, Value) VALUES ("CTRL", "VMware ESX 4.1");
INSERT IGNORE INTO OS (Project, Value) VALUES ("CTRL", "VMware ESX 5.0");
INSERT IGNORE INTO OS (Project, Value) VALUES ("CTRL", "VMware ESX 5.1");
INSERT IGNORE INTO OS (Project, Value) VALUES ("CTRL", "VMware ESX 5.5");
INSERT IGNORE INTO OS (Project, Value) VALUES ("CTRL", "VMware ESX 6.0");
INSERT IGNORE INTO OS (Project, Value) VALUES ("CTRL", "Windows 2008 IA64");
INSERT IGNORE INTO OS (Project, Value) VALUES ("CTRL", "Windows 2008 R2 IA64");
INSERT IGNORE INTO OS (Project, Value) VALUES ("CTRL", "Windows 2008 R2 x64");
INSERT IGNORE INTO OS (Project, Value) VALUES ("CTRL", "Windows 2008 x64");
INSERT IGNORE INTO OS (Project, Value) VALUES ("CTRL", "Windows 2008 x86");
INSERT IGNORE INTO OS (Project, Value) VALUES ("CTRL", "Windows 2012");
INSERT IGNORE INTO OS (Project, Value) VALUES ("CTRL", "Windows 2012 R2");
INSERT IGNORE INTO OS (Project, Value) VALUES ("CTRL", "Windows 7");
INSERT IGNORE INTO OS (Project, Value) VALUES ("CTRL", "Windows 8");
INSERT IGNORE INTO OS (Project, Value) VALUES ("CTRL", "Windows 8.1");
INSERT IGNORE INTO OS (Project, Value) VALUES ("CTRL", "Windows PE");
INSERT IGNORE INTO OS (Project, Value) VALUES ("CTRL", "Windows Vista");
INSERT IGNORE INTO OS (Project, Value) VALUES ("CTRL", "Windows XP x64");
INSERT IGNORE INTO OS (Project, Value) VALUES ("CTRL", "Windows XP x86");
INSERT IGNORE INTO OS (Project, Value) VALUES ("CTRL", "Xen Server 6.0");
INSERT IGNORE INTO OS (Project, Value) VALUES ("CTRL", "Xen Server 6.1");
